# Generated by Django 4.2.2 on 2023-07-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmethod",
            name="method",
            field=models.CharField(
                choices=[
                    ("Phone", "Phone"),
                    ("EmailFacebook", "EmailFacebook"),
                    ("Instagram", "Instagram"),
                    ("Whatsapp", "Whatsapp"),
                    ("Twitter", "Twitter"),
                    ("Other", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
