# Generated by Django 4.2.2 on 2023-07-06 01:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_alter_contact_owner_placedatecontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactTitle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("notes", models.TextField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="PlaceDateContact",
        ),
    ]
