# Generated by Django 4.2.2 on 2023-07-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_contacttitle_delete_placedatecontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(default=""),
        ),
    ]
