# Generated by Django 4.2.2 on 2023-07-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_contact_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
