# Generated by Django 4.2.2 on 2023-07-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0006_alter_contact_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmethod",
            name="method",
            field=models.CharField(
                choices=[
                    ("Phone", "Phone"),
                    ("Email", "Email"),
                    ("Facebook", "Facebook"),
                    ("Instagram", "Instagram"),
                    ("Whatsapp", "Whatsapp"),
                    ("Twitter", "Twitter"),
                    ("Other", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
