# Generated by Django 4.2.2 on 2023-06-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("formatted_address", models.TextField()),
                ("political_address", models.CharField(max_length=100)),
                (
                    "lat",
                    models.DecimalField(decimal_places=10, default=0, max_digits=13),
                ),
                (
                    "lng",
                    models.DecimalField(decimal_places=10, default=0, max_digits=13),
                ),
            ],
        ),
    ]
