# Generated by Django 4.2.2 on 2023-07-07 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("formatted_address", models.TextField()),
                ("political_address", models.CharField(max_length=100)),
                (
                    "lat",
                    models.DecimalField(decimal_places=10, default=0, max_digits=13),
                ),
                (
                    "lng",
                    models.DecimalField(decimal_places=10, default=0, max_digits=13),
                ),
                ("overview", models.TextField(default="", null=True)),
                ("types", models.JSONField(default=list)),
                (
                    "business_status",
                    models.CharField(default="", max_length=50, null=True),
                ),
                ("website", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlaceReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.IntegerField()),
                ("review", models.TextField()),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="places.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlaceContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_places",
                        to="contacts.contact",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
