# Generated by Django 4.2.2 on 2023-07-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_placereview_placecontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="business_status",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="place",
            name="overview",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="place",
            name="types",
            field=models.CharField(default="", max_length=255),
        ),
    ]
