# Generated by Django 4.2.2 on 2023-07-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0004_place_business_status_place_overview_place_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="business_status",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="overview",
            field=models.TextField(default="", null=True),
        ),
    ]
