# Generated by Django 4.2.2 on 2023-07-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0006_alter_place_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="types",
            field=models.JSONField(default=list),
        ),
    ]
