# Generated by Django 4.2.2 on 2023-07-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0007_alter_place_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="website",
            field=models.TextField(null=True),
        ),
    ]
