# Generated by Django 4.2.2 on 2023-07-05 22:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0008_place_website"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlaceContact",
        ),
    ]
