# Generated by Django 4.2.2 on 2023-07-06 01:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_contacttitle_delete_placedatecontact"),
        ("places", "0009_delete_placecontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_places",
                        to="contacts.contact",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="places.place",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contacts.contacttitle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
