# Generated by Django 4.2.2 on 2023-07-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0010_placecontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placecontact",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
