# Generated by Django 4.2.2 on 2023-07-07 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0001_initial"),
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("capacity", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Amphitheater", "Amphitheater"),
                            ("Arena", "Arena"),
                            ("Bar", "Bar"),
                            ("Brewpub", "Brewpub"),
                            ("Club", "Club"),
                            ("Coffeehouse", "Coffeehouse"),
                            ("Fair", "Fair"),
                            ("Festival", "Festival"),
                            ("House", "House"),
                            ("Listening Room", "Listening Room"),
                            ("Nightclub", "Nightclub"),
                            ("PAC", "PAC"),
                            ("Stadium", "Stadium"),
                            ("Theater", "Theater"),
                            ("Winery", "Winery"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("private", models.BooleanField(default=False)),
                (
                    "contacts",
                    models.ManyToManyField(
                        related_name="venues", to="contacts.contact"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="venues",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VenueNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField(default="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
