# Generated by Django 4.2.2 on 2023-07-04 04:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("places", "0003_placereview_placecontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("capacity", models.IntegerField()),
                ("type", models.CharField(max_length=255)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="places.place",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
