# Generated by Django 4.2.2 on 2023-07-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="private",
        ),
        migrations.AddField(
            model_name="venue",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
