# Generated by Django 4.2.2 on 2023-07-04 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0003_venuenote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venuenote",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="venues.venue",
            ),
        ),
    ]
