# Generated by Django 4.2.2 on 2023-07-04 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0007_alter_place_types"),
        ("venues", "0005_alter_venuenote_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="venues",
                to="places.place",
            ),
        ),
    ]
