# Generated by Django 4.2.2 on 2023-07-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0006_alter_venue_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuenote",
            name="created",
            field=models.DateField(auto_created=True, default="2023-07-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venuenote",
            name="last_updated",
            field=models.DateField(auto_now=True),
        ),
    ]
