# Generated by Django 4.2.2 on 2023-07-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0007_venuenote_created_venuenote_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venuenote",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
