# Generated by Django 4.2.2 on 2023-07-05 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0008_alter_venuenote_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venuenote",
            name="created",
        ),
        migrations.RemoveField(
            model_name="venuenote",
            name="last_updated",
        ),
    ]
