version: '3.1'
services:
  db:
    image: dstoffels/indietour-db:1
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - indietour-db:/var/lib/mysql
    restart: always

  api:
    image: dstoffels/indietour-api:latest
    ports:
      - 80:8000
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  indietour-db:
