version: '3.1'
services:
  db:
    image: dstoffels/indietour-db:1
    restart: always
    ports:
      - 3307:3306
    env_file:
      - .env
    volumes:
      - indietour-db:/var/lib/mysql

  api:
    build: ./
    image: dstoffels/indietour-api-dev:latest
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  nginx:
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: always

volumes:
  indietour-db:
