# Generated by Django 4.2.2 on 2023-07-03 08:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("places", "0002_remove_place_description"),
        ("dates", "0004_alter_date_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lodging",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lodgings",
                        to="dates.date",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="places.place"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
