# Generated by Django 4.2.2 on 2023-07-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="hold",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
