# Generated by Django 4.2.2 on 2023-07-04 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0004_touruser_is_admin"),
        ("venues", "0001_initial"),
        ("prospects", "0003_alter_prospect_hold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prospect",
            name="place",
        ),
        migrations.AddField(
            model_name="prospect",
            name="tour",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prospects",
                to="tours.tour",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prospect",
            name="venue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="venues.venue",
            ),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="date",
            field=models.DateField(default="2023-07-01"),
            preserve_default=False,
        ),
    ]
