# Generated by Django 4.2.2 on 2023-07-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0006_datecontact"),
        (
            "prospects",
            "0004_remove_prospect_place_prospect_tour_prospect_venue_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="confirmed_date",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_prospect",
                to="dates.date",
            ),
        ),
    ]
