# Generated by Django 4.2.2 on 2023-07-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0009_remove_venuenote_created_and_more"),
        ("prospects", "0005_prospect_confirmed_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prospect",
            name="venue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="venues.venue",
            ),
        ),
    ]
