# Generated by Django 4.2.2 on 2023-07-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0009_remove_venuenote_created_and_more"),
        ("prospects", "0006_alter_prospect_venue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prospect",
            name="venue",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="venues.venue",
            ),
            preserve_default=False,
        ),
    ]
