# Generated by Django 4.2.2 on 2023-07-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospects", "0007_alter_prospect_venue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prospect",
            name="confirmed_date",
        ),
        migrations.AddField(
            model_name="prospect",
            name="confirmed_date_id",
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
