# Generated by Django 4.2.2 on 2023-07-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospects", "0008_remove_prospect_confirmed_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prospect",
            name="confirmed_date_id",
            field=models.UUIDField(unique=True),
        ),
    ]
