# Generated by Django 4.2.2 on 2023-06-30 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0003_alter_banduser_band"),
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="band",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tours",
                to="bands.band",
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="users",
            field=models.ManyToManyField(
                related_name="users_tours", to="tours.touruser"
            ),
        ),
        migrations.AlterField(
            model_name="touruser",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tourusers",
                to="tours.tour",
            ),
        ),
    ]
