# Generated by Django 4.2.2 on 2024-02-03 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0003_alter_band_unique_together"),
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tour",
            unique_together={("band", "name")},
        ),
    ]
