# Generated by Django 4.2.2 on 2023-07-02 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0002_alter_tour_band_alter_tour_users_alter_touruser_tour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="users",
        ),
    ]
