# Generated by Django 4.2.2 on 2023-07-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0003_remove_tour_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="touruser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
