# Generated by Django 4.2.2 on 2023-06-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_band",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bands.band",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
