# Generated by Django 4.2.2 on 2023-07-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bands", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="member_bands",
            field=models.ManyToManyField(
                related_name="users", through="bands.BandUser", to="bands.band"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
