# Generated by Django 4.2.2 on 2023-07-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0004_alter_band_owner"),
        ("authentication", "0003_user_active_tour"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="member_bands",
            field=models.ManyToManyField(
                related_name="users", through="bands.BandUser", to="bands.band"
            ),
        ),
    ]
