# Generated by Django 4.2.2 on 2023-08-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_archived_bands",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_archived_tours",
            field=models.BooleanField(default=False),
        ),
    ]
