# Generated by Django 4.2.2 on 2023-08-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_user_show_archived_bands_user_show_archived_tours"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_past_dates",
            field=models.BooleanField(default=False),
        ),
    ]
