# Generated by Django 4.2.2 on 2023-07-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_user_member_bands"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="active_band",
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="active_tour",
            field=models.UUIDField(default=None, null=True),
        ),
    ]
