# Generated by Django 4.2.2 on 2024-01-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_user_show_past_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="booking_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_dates_list",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_schedule_list",
            field=models.BooleanField(default=False),
        ),
    ]
