# Generated by Django 4.2.2 on 2023-07-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="deal",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="show",
            name="hospitality",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="show",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
