# Generated by Django 4.2.2 on 2023-07-08 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0002_alter_show_deal_alter_show_hospitality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="date",
            name="venues",
        ),
        migrations.DeleteModel(
            name="Show",
        ),
    ]
