# Generated by Django 4.2.2 on 2023-06-30 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_remove_place_description"),
        ("dates", "0002_alter_date_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="date",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="places.place",
            ),
        ),
    ]
