# Generated by Django 4.2.2 on 2023-08-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0003_remove_date_venues_delete_show"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROSPECT", "PROSPECT"),
                    ("INQUIRED", "INQUIRED"),
                    ("HOLD", "HOLD"),
                    ("CHALLENGED", "CHALLENGED"),
                    ("RELEASED", "RELEASED"),
                    ("OPTION", "OPTION"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PROSPECT",
                max_length=30,
            ),
        ),
    ]
