# Generated by Django 4.2.2 on 2023-07-02 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_remove_place_description"),
        ("dates", "0003_date_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dates",
                to="places.place",
            ),
        ),
    ]
