# Generated by Django 4.2.2 on 2023-07-04 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_placereview_placecontact"),
        ("dates", "0004_alter_date_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="dates",
                to="places.place",
            ),
        ),
    ]
