# Generated by Django 4.2.2 on 2023-08-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0004_alter_date_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="hold",
            field=models.IntegerField(default=0),
        ),
    ]
