# Generated by Django 4.2.2 on 2024-01-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0005_alter_date_hold"),
    ]

    operations = [
        migrations.AddField(
            model_name="date",
            name="is_show_day",
            field=models.BooleanField(default=False),
        ),
    ]
