# Generated by Django 4.2.2 on 2024-01-21 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0006_date_is_show_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="date",
            name="hold",
        ),
        migrations.RemoveField(
            model_name="date",
            name="status",
        ),
    ]
