# Generated by Django 4.2.2 on 2024-01-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0007_remove_date_hold_remove_date_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="date",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
