# Generated by Django 4.2.2 on 2024-01-22 03:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dates", "0008_date_is_published"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogEntry",
        ),
    ]
