# Generated by Django 4.2.2 on 2023-06-27 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="band",
            name="users",
        ),
    ]
