# Generated by Django 4.2.2 on 2023-08-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
