# Generated by Django 4.2.2 on 2024-02-03 05:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bands", "0002_alter_band_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="band",
            unique_together={("name", "owner")},
        ),
    ]
