# Generated by Django 4.2.2 on 2023-06-30 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0002_remove_band_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banduser",
            name="band",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bandusers",
                to="bands.band",
            ),
        ),
    ]
