# Generated by Django 4.2.2 on 2023-07-02 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bands", "0003_alter_banduser_band"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_bands",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
