# Generated by Django 4.2.2 on 2023-07-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0004_alter_band_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="is_archived",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
