# Generated by Django 4.2.2 on 2023-07-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0001_initial"),
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shows",
                to="venues.venue",
            ),
        ),
    ]
