# Generated by Django 4.2.2 on 2024-01-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0002_alter_show_venue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="show",
            name="hold",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="show",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="shows.status",
            ),
        ),
    ]
