# Generated by Django 4.2.2 on 2024-01-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0004_alter_status_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROSPECT", "PROSPECT"),
                    ("INQUIRED", "INQUIRED"),
                    ("HOLD", "HOLD"),
                    ("CHALLENGED", "CHALLENGED"),
                    ("RELEASED", "RELEASED"),
                    ("DECLINED", "DECLINED"),
                    ("OPTION", "OPTION"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PROSPECT",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
