# Generated by Django 4.2.2 on 2024-01-22 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0006_logentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logentry",
            name="date",
        ),
        migrations.AddField(
            model_name="logentry",
            name="show",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log",
                to="shows.show",
            ),
            preserve_default=False,
        ),
    ]
