# Generated by Django 4.2.2 on 2023-06-28 01:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dates", "0001_initial"),
        ("places", "0002_remove_place_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timeslot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("details", models.TextField(blank=True, default="")),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("start_after_midnight", models.BooleanField(default=False)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("end_after_midnight", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Event", "Event"),
                            ("Travel", "Travel"),
                            ("Flight", "Flight"),
                            ("Meeting", "Meeting"),
                        ],
                        default="Event",
                        max_length=25,
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="dates.date",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeslot_destinations",
                        to="places.place",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeslot_origins",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
