# Generated by Django 4.2.2 on 2023-07-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeslots", "0002_alter_timeslot_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeslot",
            name="description",
        ),
        migrations.AddField(
            model_name="timeslot",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
