# Generated by Django 4.2.2 on 2023-07-03 06:38

from django.db import migrations, models
import timeslots.models


class Migration(migrations.Migration):
    dependencies = [
        ("timeslots", "0003_remove_timeslot_description_timeslot_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Event", "Event"),
                    ("Travel", "Travel"),
                    ("Flight", "Flight"),
                    ("Meeting", "Meeting"),
                ],
                default="Event",
                max_length=25,
            ),
        ),
    ]
