# Generated by Django 4.2.2 on 2023-07-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeslots", "0004_alter_timeslot_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="type",
            field=models.CharField(max_length=25),
        ),
    ]
