# Generated by Django 4.2.2 on 2023-07-04 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_placereview_placecontact"),
        ("timeslots", "0005_alter_timeslot_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="timeslot_destinations",
                to="places.place",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="timeslot_origins",
                to="places.place",
            ),
        ),
    ]
